// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq1VLajBtykLGd1F52Pj9R-84eTe6CYD0',
    appId: '1:525449989699:android:49b03ceaf12d3b9d8a0ef6',
    messagingSenderId: '525449989699',
    projectId: 'pdpinsta-f2ec8',
    storageBucket: 'pdpinsta-f2ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjfqLI-Uf-bQQCuf8qOEmv0uw6ILf4DOc',
    appId: '1:525449989699:ios:e31626f501a1fc2d8a0ef6',
    messagingSenderId: '525449989699',
    projectId: 'pdpinsta-f2ec8',
    storageBucket: 'pdpinsta-f2ec8.firebasestorage.app',
    androidClientId: '525449989699-7q34ra47qhkp5d4iaoluvt73uv1i9trs.apps.googleusercontent.com',
    iosClientId: '525449989699-q646uv2h250dncsuio56lumss09agvbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.manageQarzApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnPYE7aZM5wugZPraHPKcsVW3lNIvonX4',
    appId: '1:525449989699:web:c9b460c8fecf64a38a0ef6',
    messagingSenderId: '525449989699',
    projectId: 'pdpinsta-f2ec8',
    authDomain: 'pdpinsta-f2ec8.firebaseapp.com',
    storageBucket: 'pdpinsta-f2ec8.firebasestorage.app',
    measurementId: 'G-B75T85004M',
  );
}
